<?php

declare(strict_types=1);

return [
    'last_updated' => 'Last updated: :date',
    'back_home' => 'Back to home',
    'contact' => 'Questions? Contact us at :email.',
    'terms_of_service' => 'Terms of Service',
    'privacy_policy' => 'Privacy Policy',

    'terms' => [
        'page_title' => 'PandaPost Terms of Service',
        'title' => 'PandaPost Terms of Service',
        'intro' => 'These Terms of Service ("Terms") govern your access to and use of PandaPost ("the Service", "we", "us"). By creating an account or using the Service, you agree to these Terms. If you do not agree, do not use the Service.',

        'sections' => [
            [
                'heading' => '1. Eligibility',
                'body' => 'You must be at least 16 years old to use PandaPost. By using the Service, you represent that you meet this requirement and that you have the right to bind any organization on whose behalf you act.',
            ],
            [
                'heading' => '2. Account and security',
                'body' => 'You are responsible for safeguarding your credentials and for all activity under your account. You must notify us immediately of any unauthorized access. We may suspend or terminate accounts that violate these Terms or applicable law.',
            ],
            [
                'heading' => '3. Connecting third-party social accounts',
                'body' => 'PandaPost lets you connect accounts from third-party platforms (TikTok, Meta/Facebook/Instagram/Threads, X, LinkedIn, YouTube, Pinterest, Bluesky, Mastodon, Google Drive, and others) via OAuth. You authorize PandaPost to act on your behalf only within the scopes you explicitly grant. You can disconnect any account at any time from your workspace settings, which revokes our stored tokens.',
            ],
            [
                'heading' => '4. Your content',
                'body' => 'You retain full ownership of the content you upload or schedule through PandaPost ("Your Content"). You grant PandaPost a limited, non-exclusive license to store, process, and transmit Your Content solely to operate the Service — including publishing it to the third-party platforms you instruct us to publish on. You are solely responsible for Your Content and for compliance with each platform\'s terms.',
            ],
            [
                'heading' => '5. Acceptable use',
                'body' => 'You agree not to use PandaPost to publish content that is unlawful, infringing, abusive, deceptive, or that violates the terms of any connected platform. We may remove content or terminate accounts that breach this policy.',
            ],
            [
                'heading' => '6. Subscriptions and billing',
                'body' => 'Paid plans are billed through Stripe. Fees are charged in advance for the selected billing cycle. You can cancel at any time; cancellation takes effect at the end of the current cycle and no refund is issued for partial periods unless required by law.',
            ],
            [
                'heading' => '7. AI features',
                'body' => 'PandaPost offers AI-assisted features (drafting, refining, translating content). Outputs are generated by third-party AI providers and may be inaccurate. You are responsible for reviewing AI output before publishing.',
            ],
            [
                'heading' => '8. Service availability',
                'body' => 'We provide PandaPost on an "as is" and "as available" basis. We do not guarantee uninterrupted operation. Third-party platforms may change their APIs or rate limits at any time, which can affect publishing.',
            ],
            [
                'heading' => '9. Limitation of liability',
                'body' => 'To the maximum extent permitted by law, PandaPost is not liable for indirect, incidental, or consequential damages, or for loss of data, profits, or business arising from your use of the Service.',
            ],
            [
                'heading' => '10. Termination',
                'body' => 'You can delete your account at any time from settings. Upon deletion we erase or anonymize your personal data within 30 days, except where retention is required by law (e.g., financial records).',
            ],
            [
                'heading' => '11. Changes to these Terms',
                'body' => 'We may update these Terms from time to time. Material changes will be communicated by email or in-app notice at least 14 days before they take effect. Continued use after the effective date constitutes acceptance.',
            ],
            [
                'heading' => '12. Governing law',
                'body' => 'These Terms are governed by the laws of Brazil. Any dispute will be resolved in the courts of the user\'s domicile when consumer law applies, and otherwise in the courts of São Paulo, SP, Brazil.',
            ],
        ],
    ],

    'privacy' => [
        'page_title' => 'PandaPost Privacy Policy',
        'title' => 'PandaPost Privacy Policy',
        'intro' => 'This Privacy Policy explains how PandaPost ("we", "us") collects, uses, and protects your personal data. We comply with the Brazilian General Data Protection Law (LGPD) and the EU General Data Protection Regulation (GDPR) where applicable.',

        'sections' => [
            [
                'heading' => '1. Data we collect',
                'body' => 'When you sign up, we collect your name, email, password (hashed), preferred language and timezone. If you sign in with Google or GitHub, we receive your profile email and public profile data from those providers. When you connect a social platform (TikTok, Meta, X, LinkedIn, YouTube, Pinterest, Bluesky, Mastodon, Threads, Google Drive), we store OAuth access and refresh tokens encrypted at rest, plus the platform user ID and display name so we can show you which account is connected.',
            ],
            [
                'heading' => '2. Content you provide',
                'body' => 'We store the posts, captions, media files, and schedules you create. Media is stored in our object storage and may be processed (resized, transcoded) to meet each platform\'s requirements. We never use Your Content to train AI models.',
            ],
            [
                'heading' => '3. Use of TikTok data',
                'body' => 'When you connect your TikTok account, the app accesses public profile information (username, display name, avatar) and video metrics (likes, views, comments) via official TikTok API OAuth. This data is used exclusively to display statistics in the user\'s dashboard and is never sold, shared, or used for advertising. The app only publishes scheduled videos on behalf of the user. The user can disconnect their account at any time in settings or revoke access directly via their TikTok account settings (Security and login -> Manage app access).',
            ],
            [
                'heading' => '4. Payments',
                'body' => 'Payments are processed by Stripe. We do not store your credit card data on our servers — Stripe stores it under their PCI-DSS certified infrastructure. We store only a Stripe customer ID and subscription status.',
            ],
            [
                'heading' => '5. Cookies and analytics',
                'body' => 'We use essential cookies for authentication and session management. We may use privacy-respecting analytics (PostHog) to understand product usage in aggregate. We do not run third-party advertising trackers.',
            ],
            [
                'heading' => '6. Email',
                'body' => 'We send transactional emails (account verification, invite notifications, billing receipts, security alerts). We do not send marketing emails without your explicit opt-in.',
            ],
            [
                'heading' => '7. Data sharing',
                'body' => 'We share data only with: (a) the social platforms you connect, exclusively to publish content you instruct us to publish; (b) Stripe, for payment processing; (c) infrastructure providers (hosting, email) acting as data processors under contract; (d) authorities when legally required.',
            ],
            [
                'heading' => '8. Data retention',
                'body' => 'We retain your account data while your account is active. After account deletion, we erase or anonymize personal data within 30 days, except where retention is required by law (e.g., invoices kept for 5 years).',
            ],
            [
                'heading' => '9. Your rights',
                'body' => 'Under LGPD and GDPR you have the right to access, correct, export, restrict processing of, or delete your personal data. You can exercise these rights from your account settings or by contacting us at the email below.',
            ],
            [
                'heading' => '10. Security',
                'body' => 'We use HTTPS for all traffic, encrypt OAuth tokens and sensitive fields at rest, and follow industry best practices for application security. No system is perfectly secure, however; please use a strong, unique password.',
            ],
            [
                'heading' => '11. International transfers',
                'body' => 'Our servers and processors may be located outside your country. When we transfer your data across borders, we rely on Standard Contractual Clauses or equivalent safeguards.',
            ],
            [
                'heading' => '12. Children',
                'body' => 'PandaPost is not intended for users under 16. We do not knowingly collect personal data from children under 16; if you believe we have, please contact us so we can delete it.',
            ],
            [
                'heading' => '13. Changes to this policy',
                'body' => 'We may update this Privacy Policy. Material changes will be communicated by email or in-app notice at least 14 days before they take effect.',
            ],
        ],
    ],
];
